Disable build and test result collection steps
Comment out build and test result collection steps for now.

diff --git a/.cloudbees/workflows/build.yaml b/.cloudbees/workflows/build.yaml
--- a/.cloudbees/workflows/build.yaml
+++ b/.cloudbees/workflows/build.yaml
@@ -13,11 +13,12 @@ jobs:
         kind: build
         shell: sh
         run: |
-          ./gradlew build
-          find .
-      - uses: cloudbees-io/publish-test-results@v1
-        name: collect tests
-        if: success() || failure()
-        with:
-          test-type: JUNIT
-          folder-name: "**/build/test-results/**/TEST-*.xml"
+          echo "TODO: run a real build of this repo..."
+          # ./gradlew build
+          # find .
+      # - uses: cloudbees-io/publish-test-results@v1
+      #   name: collect tests
+      #   if: success() || failure()
+      #   with:
+      #     test-type: JUNIT
+      #     folder-name: "**/build/test-results/**/TEST-*.xml"
